# Generated by Django 5.1.6 on 2025-02-18 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='author',
            field=models.TextField(verbose_name='Author'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='context',
            field=models.TextField(verbose_name='Text Content'),
        ),
    ]
