# Generated by Django 5.1.6 on 2025-02-19 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0004_alter_quote_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quote',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='quote',
            old_name='context',
            new_name='content',
        ),
    ]
